//! Core eSpeak NG phoneme data, embedded at compile time.
//!
//! Contains the binary phoneme tables, language definitions, and voice
//! definitions shared by all languages:
//!
//! | File | Description |
//! |------|-------------|
//! | `phondata` | Formant frame sequences and WAV samples |
//! | `phonindex` | Phoneme bytecode index |
//! | `phontab` | Phoneme name/attribute table |
//! | `intonations` | Intonation contour data |
//! | `lang/*` | Language definition files (145 languages) |
//! | `voices/*` | Voice definition files (200 voices) |
//! | `mbrola_ph/*` | MBROLA phoneme mappings |
//!
//! ## Usage
//!
//! ```rust,no_run
//! use std::path::Path;
//!
//! // Install all files into a directory (e.g. a temp dir)
//! let data_dir = Path::new("/tmp/espeak-data");
//! std::fs::create_dir_all(data_dir).unwrap();
//! espeak_ng_data_phonemes::install(data_dir).unwrap();
//! ```

// Generated by build.rs — contains `ALL_FILES: &[(&str, &[u8])]`.
include!(concat!(env!("OUT_DIR"), "/files.rs"));

/// Install all embedded data files into `dest_dir`.
///
/// Creates any missing subdirectories.  Existing files are silently
/// overwritten.  This is idempotent — calling it multiple times on the
/// same directory is safe.
///
/// # Errors
/// Returns an [`std::io::Error`] if a directory cannot be created or a
/// file cannot be written.
pub fn install(dest_dir: &std::path::Path) -> std::io::Result<()> {
    for (rel_path, data) in ALL_FILES {
        let dest = dest_dir.join(rel_path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(dest, data)?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_files_nonempty() {
        assert!(!ALL_FILES.is_empty(), "ALL_FILES must not be empty");
        for (path, data) in ALL_FILES {
            assert!(!data.is_empty(), "embedded file {path:?} is empty");
        }
    }
}
